version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001 # console access is not required for automated tests, but keeping it here for ease of debugging
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password